import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#0b1830'
  },

  ImgContainer:{
    width:150,
    height:150,
    overflow:'hidden',
    borderRadius:'50%',
    margin:20
  },

  Img:{
    width:150,
    height:150,
    borderRadius:'50%',

  },
  ImgMainContainer:{
    flexDirection:'row',
    justifyContent:'center'
  },
  TeamDetailInfo:{
    backgroundColor:'#1f2937',
    width:'80%',
    height:200,
    borderRadius:10
  },
  TeamInfoMainContainer:{
    flexDirection:'row',
    justifyContent:'center'
  },
  TeamInfoTitle:{
    color:'#fff',
    fontSize:24,
    fontWeight:'bold',
    textAlign:'center',
    paddingTop:10,
    paddingBottom:5
  },
  TeamInfoPlayersCount:{
    color:'#fff',
    fontSize:16,
    paddingLeft:10,
    paddingBottom:50
  },
  ButtonsContainer:{
    flexDirection:'row',
    justifyContent:'space-around',
    alignItems:'center'
  },
  EditBtnContainer:{
    backgroundColor:'#d08700',
    paddingVertical:10,
    paddingHorizontal:20,
    borderRadius:10
  },
  EditBtnTitle:{
    color:'#fff',
    fontWeight:'bold',
    flexDirection:'row',
    justifyContent:'center',
    alignItems:'center'
  },
  DeleteBtnContainer:{
    backgroundColor:'#e7000b',
    paddingVertical:10,
    paddingHorizontal:20,
    borderRadius:10
  },
  playerContainer:{
    flexDirection:'row',
    justifyContent:'space-between',
    paddingHorizontal:40,
    paddingTop:40,
    alignItems:'center'
  },
  playerTitle:{
    color:'#fff',
    fontSize:16,
    fontWeight:'bold'
  },
  AddBtnContainer:{
    flexDirection:'row',
    alignItems:'center',
    backgroundColor:'#00c951',
    borderRadius:10,
    paddingVertical:10,
    paddingHorizontal:20
  },
  AddPlayerBtn:{
    color:'#fff',
    fontSize:16,
    fontWeight:'bold'
  }
})