import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overviewContainer:{
    backgroundColor:'#0b1b33',
    flex:1
  },
  header:{
    flexDirection:'column',
    paddingVertical:30,
    alignItems:'center'
  },
  image:{
    width:150,
    height:150
  },
  headerCardContainer:{
    flexDirection:'column',
    gap:10,
    marginVertical:20,
    backgroundColor:'#122240',
    padding:20,
    borderRadius:10
  },

  headerCard:{
    width:200,
    height:60,
    borderColor:'#233554',
    backgroundColor:'#233554',
    borderRadius:10,
    color:'#fff',
    padding:10
  },
  headerCardText:{
    color:'#7c828f',
    fontWeight:'bold',
    textAlign:'center'
  },
  headerCardTitleContainer:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'center',
    gap:5
  },
  headerCardBottomContainer:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'center'
  },
  headerCardBottomContainerInnerText:{
    color:'#fff',
    fontWeight:'bold'
  },
  tournamentTimeLineContainer:{
    backgroundColor:'#122240',
    gap:10,
    height:110,
    width:240,
    borderRadius:10
  },
  timeLineTextContainer:{
    flexDirection:'row',
    justifyContent:"center",
    alignItems:'center',
    gap:5
  },
  timeLineText:{
    color:'#fff',
    fontSize:16,
    fontWeight:'bold',
    paddingVertical:10
  },
  timeRangeContainer:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'center',
    gap:20,
    paddingTop:10
  },
  timeRangeText:{
    color:'#fff',
    fontWeight:'bold'
  },
})